# Generated by Django 3.0.5 on 2020-05-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans19', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='case_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
