# Generated by Django 3.0.5 on 2020-04-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans19', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visit_number',
        ),
    ]
